version: '3'

services:
  docker-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  app:
    image: api-consumidor
    ports:
      - 9090:9090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
      USERNAME: root
      PASSWORD: root
    depends_on:
      - docker-mysql