# Server
server:
  port: 9090
  max-http-header-size: 2147483647


## database settings
##spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/db_desafio
spring.datasource.username: root
spring.datasource.password: root
spring.jpa.show-sql: true





